version: 2

jobs:
# The install job for all dependencies so we can reuse/depend on it in other jobs
  install_dependencies:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v9-dependencies-{{ checksum "yarn.lock" }}{{ checksum "server/yarn.lock" }}
            - v9-dependencies-
      - run: yarn
      - run: cd server && yarn
      - run: sudo apt-get install tree # for debugging circle builds
      - run: tree -Ca
      - run: node -v
      - run: npm -v
      - save_cache:
          paths:
            - .yarn
            - .cache
            - project/server/node_modules
          key: v9-dependencies-{{ checksum "yarn.lock" }}{{ checksum "server/yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - .yarn
            - .cache
            - project/server/node_modules

# Running all tests
  testing:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: yarn
      - run:
          name: Testing our code
          command: yarn test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


workflows:
  version: 2
  running_jobs:
    jobs:
      - install_dependencies       # First we install dependencies
      - testing:                   # Second we test our code
          requires:
            - install_dependencies
