version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  # The install job for all dependencies so we can reuse/depend on it in other jobs
  install_dependencies:
    docker:
      - image: cypress/included:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v10-dependencies-{{ checksum "yarn.lock" }}{{ checksum "server/yarn.lock" }}
            - v10-dependencies-
      - run:
          name: Install dependencies for app
          command: yarn
      - run:
          name: Install dependencies for server
          command: cd server && yarn
      - run:
          name: Adding debugging deps
          command: sudo apt-get install tree # for debugging circle builds
      - run:
          name: Report file structure
          command: tree -Ca
      - run:
          name: Node version
          command: node -v
      - run:
          name: npm version
          command: npm -v
      - run:
          name: Yarn version
          command: yarn --version
      - save_cache:
          paths:
            - .yarn
            - .cache
          key: v10-dependencies-{{ checksum "yarn.lock" }}{{ checksum "server/yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - .yarn
            - .cache

  # Running all tests
  testing:
    docker:
      - image: cypress/included:lts
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Installing dependencies from cache
          command: yarn
      - run:
          name: Installind dependencies for server from cache
          command: cd server && yarn
      # - run:
      #     name: Installing Cypress dependencies
      #     command: sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - run:
          name: Testing our code
          command: yarn test
      - store_artifacts:
          path: src/tests/utils/videos
      - store_artifacts:
          path: src/tests/utils/screenshots


workflows:
  version: 2
  running_jobs:
    jobs:
      - install_dependencies # First we install dependencies
      - testing:             # Second we test our code
          requires:
            - install_dependencies
